spring:
  application:
    name: poc-transactional-outbox-pattern
  datasource:
    url: jdbc:postgresql://localhost:5432/outbox
    username: outbox
    password: outbox
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: notificacao-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

outbox:
  poller:
    fixed-delay-ms: 2000

server:
  port: 8080
